-- Table races (mise à jour v2 — 129 races)
CREATE TABLE IF NOT EXISTS races (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  nom text NOT NULL UNIQUE,
  categorie text,
  grand_gabarit boolean DEFAULT false,
  actif boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- Insérer toutes les races (ré-exécutable sans risque)
INSERT INTO races (nom, categorie, grand_gabarit) VALUES
('Croisé / Mix', 'Mixte', false),
('Race inconnue', 'Mixte', false),
('Autre', 'Autre', false),
('Labrador Retriever', 'Retrievers', true),
('Golden Retriever', 'Retrievers', true),
('Flat Coated Retriever', 'Retrievers', true),
('Nova Scotia Duck Tolling Retriever', 'Retrievers', false),
('Berger Allemand', 'Bergers', true),
('Berger Australien', 'Bergers', false),
('Berger Suisse Blanc', 'Bergers', true),
('Berger Belge Malinois', 'Bergers', true),
('Berger Belge Tervueren', 'Bergers', true),
('Berger Belge Groenendael', 'Bergers', true),
('Berger Belge Laekenois', 'Bergers', true),
('Berger Hollandais', 'Bergers', true),
('Berger Catalan', 'Bergers', true),
('Berger des Shetland', 'Bergers', false),
('Border Collie', 'Bergers', false),
('Colley', 'Bergers', true),
('Bouvier Australien', 'Bergers', false),
('Bouvier Bernois', 'Bergers', true),
('Cane da Pastore Maremmano', 'Bergers', true),
('Kangal', 'Bergers', true),
('Husky Sibérien', 'Nordiques', true),
('Samoyède', 'Nordiques', true),
('Spitz Nain / Poméranien', 'Nordiques', false),
('Akita Inu', 'Asiatiques', true),
('Shiba Inu', 'Asiatiques', false),
('Chow Chow', 'Asiatiques', true),
('Basenji', 'Asiatiques', false),
('Jack Russell Terrier', 'Terriers', false),
('Parson Russell Terrier', 'Terriers', false),
('Yorkshire Terrier', 'Terriers', false),
('Airedale Terrier', 'Terriers', false),
('Fox Terrier', 'Terriers', false),
('Bull Terrier', 'Terriers', false),
('Staffordshire Bull Terrier', 'Terriers', false),
('American Staffordshire Terrier', 'Terriers', true),
('Schnauzer', 'Terriers', false),
('West Highland Terrier', 'Terriers', false),
('Pitbull Type', 'Molossoïdes', true),
('American Bully', 'Molossoïdes', true),
('Cane Corso', 'Molossoïdes', true),
('Rottweiler', 'Molossoïdes', true),
('Dobermann', 'Molossoïdes', true),
('Boxer', 'Molossoïdes', true),
('Dogue Allemand', 'Molossoïdes', true),
('Mastiff', 'Molossoïdes', true),
('Terre-Neuve', 'Molossoïdes', true),
('Saint-Bernard', 'Molossoïdes', true),
('Shar Pei', 'Molossoïdes', false),
('Bouledogue Français', 'Molossoïdes', false),
('Bouledogue Anglais', 'Molossoïdes', false),
('Carlin', 'Petites races', false),
('Chihuahua', 'Petites races', false),
('Teckel', 'Petites races', false),
('Shih Tzu', 'Petites races', false),
('Bichon Maltais', 'Petites races', false),
('Bichon Frisé', 'Petites races', false),
('Cavalier King Charles', 'Petites races', false),
('Beagle', 'Chiens courants', false),
('Basset Hound', 'Chiens courants', false),
('Cocker Spaniel', 'Spaniels', false),
('Épagneul Breton', 'Spaniels', false),
('Setter Anglais', 'Setters', true),
('Setter Irlandais', 'Setters', true),
('Caniche', 'Caniche', false),
('Cockapoo', 'Croisés populaires', false),
('Labradoodle', 'Croisés populaires', true),
('Goldendoodle', 'Croisés populaires', true),
('Dalmatien', 'Divers', true),
('Weimaraner', 'Braque', true),
('Vizsla', 'Braque', true),
('Braque Français', 'Braque', true),
('Rhodesian Ridgeback', 'Divers', true),
('Lévrier Galgo', 'Lévriers', true),
('Whippet', 'Lévriers', false),
('Greyhound', 'Lévriers', true),
('Podengo Portugais', 'Divers', false),
('Beauceron', 'Bergers', true),
('Briard', 'Bergers', true),
('Bouvier des Flandres', 'Bergers', true),
('Berger des Pyrénées', 'Bergers', false),
('Bobtail', 'Bergers', true),
('Welsh Corgi Pembroke', 'Bergers', false),
('Schipperke', 'Petites races', false),
('Dogue de Bordeaux', 'Molossoïdes', true),
('Bullmastiff', 'Molossoïdes', true),
('Léonberg', 'Molossoïdes', true),
('Landseer', 'Molossoïdes', true),
('Dogo Argentino', 'Molossoïdes', true),
('Mâtin Napolitain', 'Molossoïdes', true),
('Dogue du Tibet', 'Molossoïdes', true),
('Fila Brasileiro', 'Molossoïdes', true),
('Tosa Inu', 'Molossoïdes', true),
('Berger du Caucase', 'Bergers', true),
('Berger d''Anatolie', 'Bergers', true),
('Malamute d''Alaska', 'Nordiques', true),
('Eurasier', 'Nordiques', false),
('Keeshond (Spitz Loup)', 'Nordiques', false),
('Épagneul Tibétain', 'Asiatiques', false),
('Lhassa Apso', 'Petites races', false),
('Coton de Tuléar', 'Petites races', false),
('Cairn Terrier', 'Terriers', false),
('Border Terrier', 'Terriers', false),
('Scottish Terrier', 'Terriers', false),
('Welsh Terrier', 'Terriers', false),
('Bichon Havanais', 'Petites races', false),
('Boston Terrier', 'Petites races', false),
('Pékinois', 'Petites races', false),
('Épagneul Papillon', 'Petites races', false),
('Spitz Japonais', 'Petites races', false),
('Petit Lévrier Italien', 'Lévriers', false),
('English Springer Spaniel', 'Spaniels', false),
('Cocker Américain', 'Spaniels', false),
('Setter Gordon', 'Setters', true),
('Braque Allemand', 'Braque', false),
('Pointer Anglais', 'Braque', false),
('Chesapeake Bay Retriever', 'Retrievers', true),
('Barzoï', 'Lévriers', true),
('Lévrier Afghan', 'Lévriers', false),
('Lévrier Écossais (Deerhound)', 'Lévriers', true),
('Lévrier Irlandais', 'Lévriers', true),
('Chien d''eau Portugais', 'Divers', false),
('Lagotto Romagnolo', 'Divers', false),
('Barbet', 'Divers', false),
('Pinscher Allemand', 'Divers', false),
('Pinscher Nain', 'Petites races', false),
('Berger Picard', 'Bergers', false)
ON CONFLICT (nom) DO NOTHING;
